- name: Ensure Supervisor is installed
  apt: name=supervisor state=present update_cache=yes

- name: Create Supervisor template
  template:
    src: supervisor_app.conf.j2
    dest: "/etc/supervisor/conf.d/{{app_name}}.conf"

- name: Stop Supervisor for App
  service: name=supervisor state=stopped

- name: Pause for Restart to take effect
  pause: seconds=2

- name: Start Supervisor for App
  service: name=supervisor state=started
  notify:
    - restart nginx